spring:
  application:
    name: Default

logging:
  level:
    root: debug

server:
  port: 8080

client:
  hello:
    target: localhost:${server.port}
  helloopen:
    target: localhost:${server.port}

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full